<?php

function amp_text_format_filter_info()
{
    $filters = array();
    $filters['amp_filter'] = array(
        'title' => t('AMP tag converter'),
        'description' => t('Convert html tags to amp-tags'),
        'process callback'  => '_amp_filter_process',
    );
    return $filters;
}

function _amp_filter_process($text, $filter, $format)
{
    if (module_exists('amp') && amp_is_amp_request()) {
        $text = str_ireplace(
            ['<img','<video','/video>','<audio','/audio>'],
            ['<amp-img','<amp-video','/amp-video>','<amp-audio','/amp-audio>'],
            $text
        );
        
        $text = preg_replace('/<amp-img(.*?)>/', '<amp-img$1></amp-img>', $text);
    }
    
    return $text;
}
